name: Execution Programm√©e
on:
  schedule:
    # Syntaxe : "Minutes Heures Jour_du_mois Mois Jour_de_la_semaine"
    # Attention : L'heure est en UTC (souvent 1h ou 2h de moins que la France)
    - cron: '2 18 * * *'
  workflow_dispatch: # Permet aussi de le lancer manuellement pour tester

jobs:
  run-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Installer les modules
        run: npm install  # Cela va lire votre package.json
      - run: node index.js
