name: Update Dates List
on:
  push:
    paths:
      - 'data/clan/*.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate dates.json
        run: |
          cd data/clan
          ls *.json | sed 's/\.json//' | jq -R . | jq -s 'sort | reverse' > ../../dates.json
      - name: Commit and push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add dates.json
          git commit -m "Auto-update dates.json" || exit 0
          git push
