name: Update Dates List
on:
  push:
    paths:
      - 'data/clan/**' # Se déclenche quand on ajoute des données de clan

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate dates.json
        run: |
          # Lister les fichiers .json sans l'extension, trier et créer le tableau JSON
          cd data/clan
          ls -1 *.json | sed 's/\.json$//' | jq -R -s -c 'split("\n") | map(select(length > 0)) | sort | reverse' > ../../dates.json
          
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dates.json
          git commit -m "Mise à jour automatique de dates.json" || echo "Pas de changements"
          git push
